version: '3' 
services:
  web:  # Service for the Nginx web server
    image: nginx:latest  # Use the official Nginx image from Docker Hub
    ports:
      - "80:80"  # Map host port 80 to container port 80

  api:  # Service for the Node.js API server
    build: ./api  # Build the API service using the Dockerfile in the "./api" directory
    ports:
      - "3000:3000"  # Map host port 3000 to container port 3000
    volumes:
      - ./api:/app  # Mount the local "./api" directory into the container's "/app" directory
